# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 285473a1a71e88c1a78aa324e8f996e13c3c9e54bc8513d6b6adbd2d023d2557641c0eb30b6b8efc6a1b1aa317781ab5a1ef2821f01c0539f06f93664d4e8232

test:
  secret_key_base: 84545196cb4a9b4bd4388d8143529746b98ffcc8740f27b3adaa126035e248df1caadd9aa7a2016501550282213df87c01140b85473570da278e47bcddcdeeec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
